baseURL               = "https://tsai97216.github.io/tools/"
languageCode          = "zh-TW"             
title                 = "Chi 的工具箱"
# theme               = "WebStack-Hugo"      
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author            = "tsai97216"
    description       = "我的個人資源導航站"
    
    # 側邊欄按鈕連結
    upload            = "https://github.com/tsai97216/tools/issues"                  
    about             = "/about/"                  
    repository        = "https://github.com/tsai97216/tools"
    
    # 載入動畫設定
    enablePreLoad     = true
    textPreLoad       = "正在載入..."        
    
    # 側邊欄預設展開
    expandSidebar     = true
    
    # 圖片路徑設定
    logosPath         = "assets/images/logos"
    defaultLogo       = "assets/images/logos/default.webp"
    
    # 預設開啟夜間模式
    nightMode         = true
    
    # 關閉主題內建一言
    yiyan             = false
    
    # 開啟圖片燈箱
    fancybox          = true

[params.seo]    
    googleAnlyticsId  = ""
    GoogleAdsClient   = ""

[params.images]
    favicon           = "assets/images/bi-favicon.png"
    
    # 首頁大搜尋框背景
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"
    
    # 側邊欄 Logo
    logoExpandLight   = "assets/images/bi-expand-dark.png"
    logoExpandDark    = "assets/images/bi-expand-light.png"
    logoCollapseLight = "assets/images/bi.png"
    logoCollapseDark  = "assets/images/bi.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2025 Tsai97216 | Powered by GitHub Pages'

# ====================================================
# 頂部導航分區選單 (對應四大分類)
# ====================================================

[[menu.main]]
  name = "首頁推薦"
  pre = "<i class='fas fa-home fa-lg'></i>"
  url = "#term-0"
  weight = 1

[[menu.main]]
  name = "影音娛樂社群"
  pre = "<i class='fas fa-share-alt fa-lg'></i>"
  url = "#term-1"
  weight = 2

[[menu.main]]
  name = "動漫遊戲"
  pre = "<i class='fas fa-gamepad fa-lg'></i>"
  url = "#term-2"
  weight = 3

[[menu.main]]
  name = "實用工具"
  pre = "<i class='fas fa-tools fa-lg'></i>"
  url = "#term-3"
  weight = 4
