baseURL               = "https://tsai97216.github.io/tools/"
languageCode          = "zh-TW"             
title                 = "Chi 的工具箱"
# theme               = "WebStack-Hugo"     
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author            = "tsai97216"
    description       = "我的個人資源導航站"
    upload            = ""                  
    about             = ""                  
    repository        = "https://github.com/tsai97216/tools"
    enablePreLoad     = true
    textPreLoad       = "正在載入..."        
    expandSidebar     = true
    logosPath         = "assets/images/logos"
    defaultLogo       = "assets/images/logos/default.webp"
    nightMode         = true
    yiyan             = true
    fancybox          = true

[params.seo]    
    baiduhmid         = ''
    baiduSiteVer      = ''
    tj51laid          = ''
    tj51lack          = ''
    GoogleAdsClient   = ''

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/bi-favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"
    logoExpandLight   = "assets/images/bi-expand-dark.png"
    logoExpandDark    = "assets/images/bi-expand-light.png"
    logoCollapseLight = "assets/images/bi.png"
    logoCollapseDark  = "assets/images/bi.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2025 Tsai97216 | Powered by GitHub Pages'
